### ISSUE TITLE
Implementing OSSF Scorecard

### ISSUE THREAD

**Issue by UlisesGascon** [expressjs/security-wg#2]
Some time ago, we implemented the monitoring and review of the [OSSF scorecard](https://securityscorecards.dev/) in the Node.js org, and it significantly contributed to the improvement of many repositories. I believe adopting a similar approach for Express would be highly beneficial. We've developed tools, such as the [OpenSSF Scorecard Monitor](https://github.com/marketplace/actions/openssf-scorecard-monitor) and [OpenSSF Scorecard Visualizer](https://github.com/KoolTheba/openssf-scorecard-api-visualizer), along with processes that make handling the evolution of scoring straightforward. Despite initial appearances, the process is quite simple.

**Context**
> The goal of Scorecards is to auto-generate a “security score” for open source projects to help users as they decide the trust, risk, and security posture for their use case. This data can also be used to augment any decision making in an automated fashion when new open source dependencies are introduced inside projects or at organizations. For example, organizations may decide that any new dependency with low scores has to go through additional evaluation. These checks could help mitigate malicious dependencies from getting deployed to production systems like we’ve seen recently with [malicious NPM packages](https://portswigger.net/daily-swig/open-source-security-malicious-npm-packages-broadcast-sensitive-user-data-online). 
> source: [openssf Blog](https://openssf.org/blog/2020/11/06/security-scorecards-for-open-source-projects/)

**Resources**

- [OpenSSF Scorecard](https://securityscorecards.dev/)
- [You should use the OpenSSF Scorecard](https://blog.ulisesgascon.com/openssf-scorecard-in-nodejs)
- [OpenSSF Scorecard API](https://api.securityscorecards.dev/#/results)
- [Security Scorecards for Open Source Projects](https://openssf.org/blog/2020/11/06/security-scorecards-for-open-source-projects/)

**Next Steps:**

- [x]  Define when/how to review the scoring as a team. For example, in Node.js, we conduct this review in every Security WG Meeting. [Watch example (minute 04:00 to 10:00)](https://www.youtube.com/live/ZKKyUVbPY24?si=Nx-orOq3A_hEI9gA&t=237) and [the dashboard](https://github.com/nodejs/security-wg/blob/main/tools/ossf_scorecard/report.md)
- [x]  Add the Scorecard pipelines to the projects. [View example](https://github.com/ada-url/ada/pull/235/files)
- [x]  Improve the scoring by patching the bugs. [See example](https://github.com/ada-url/ada/pull/438)

I'm enthusiastic about leading these changes in the repos. While we may not be familiar with the OSSF Scorecard, we already have scores for most of our projects. [Here is a simple dashboard that I auto-generated](https://github.com/UlisesGascon/openssf-scorecard-monitor-demo/blob/main/experimental_expressjs/report.md). The OSSF team is already tracking our projects using a CRON job, but we can easily enrich them and make some simple patches to increase the scoring.

Most of these changes won't require significant alterations and can be performed in isolated PRs, making them easy to review. If we're in agreement, I can start with the Express project to showcase the process. 👍

**Comment by inigomarquinez** [comment]
Good afternoon!

I've had a chat with @UlisesGascon to tell him that I am interested in contributing to this initiative, as the OpenSSF Scorecard is something that I like and that I have also helped to implement in the Open Source community of the company where I work.

**Comment by UlisesGascon** [comment]
Yeah! Welcome aboard @inigomarquinez 🎉

**Comment by carpasse** [comment]
Good Morning!

I've also had a chat with @UlisesGascon  and I am interested in contributing to this initiative too.

**Comment by UlisesGascon** [comment]
As discussed with @inigomarquinez, he will champion the initiative.

**Comment by UlisesGascon** [comment]
We have a dashboard now https://github.com/expressjs/security-wg/blob/main/tools/ossf_scorecard/report.md and a GitHub Action to update the reports :partying_face:

**Comment by inigomarquinez** [comment]
We can say that the implementation of the scorecard has been completed in most of the organisations' repositories [expressjs](https://github.com/expressjs), [pillarjs](https://github.com/pillarjs) and [jshttp](https://github.com/jshttp). The implementation has been the same in all cases, adding a github action in each repository called scorecard.yml (see example [here](https://github.com/expressjs/body-parser/blob/master/.github/workflows/scorecard.yml)). This action is executed both with each push to `master` and weekly via a cronjob.

Some repositories of the 3 organisations have been discarded and the scorecard has not been integrated in them for several reasons: they have been deprecated, they have not been updated for a long time (more than 10 years), they are not applicable (documentation repositories) or they have a very low level of downloads and it is more than likely that in the near future they will be archived.

After finalising the integration, the next step is to analyse the scores in the individual repositories and take suggested actions to improve these scores.

@UlisesGascon , should we mark this issue as closed?

**Comment by UlisesGascon** [comment]
Thanks for all the hard work @inigomarquinez and @carpasse! 

> @UlisesGascon , should we mark this issue as closed?

I prefer to keep it open until the PRs related to the Express repo are merged, so we can have a clear policy on how to patch the other repositories.

**Comment by wesleytodd** [comment]
Looks like some of them are broken. maybe @carpasse or @inigomarquinez, do you have time to look into it? https://github.com/jshttp/http-errors/actions/runs/11797478580/job/32861554162

**Comment by carpasse** [comment]
@wesleytodd I will try to take a look at the broken ones this week.

**Comment by carpasse** [comment]
I've run a [bash script](https://gist.github.com/carpasse/a8e639e8ee6a3e6dbb03c2eed1dc9898) to identify repositories with a failed **Scorecard Workflow Action**. Below is the list of affected repositories organized by organization.  

I plan to address them over the next month, but if anyone can take on any of these, please mark it in the checklist below to avoid duplication of effort.

### Organization: **expressjs**
- [ ] expressjs/errorhandler  
- [ ] expressjs/cors  
- [ ] expressjs/session  
- [ ] expressjs/multer  
- [ ] expressjs/serve-index  
- [ ] expressjs/cookie-session  
- [ ] expressjs/method-override  
- [ ] expressjs/serve-favicon  

### Organization: **pillarjs**
- [ ] pillarjs/router  

### Organization: **jshttp**
- [ ] jshttp/mime-db  
- [ ] jshttp/http-errors  
- [ ] jshttp/content-disposition  
- [ ] jshttp/accepts  
- [ ] jshttp/mime-types  
- [ ] jshttp/basic-auth  
- [ ] jshttp/etag  

Feel free to tackle any of these. Just check the box to indicate you're working on it. Thanks!

**Comment by carpasse** [comment]
@wesleytodd , could you please review the PR for HTTP Errors? I looked into the issue with @UlisesGascon , and it’s not failing due to a problem with the code itself but because it can’t obtain the certificate needed to publish the results ([link](https://github.com/jshttp/http-errors/actions/runs/12361615409/job/34499158296#step:4:1167)). This issue seems to be outside the control of the GitHub Actions. I was hoping that updating the scorecard action dependency might "fix" it.

**Comment by carpasse** [comment]
@expressjs/express-tc As @jonkoops mentioned in this [comment](https://github.com/pillarjs/router/pull/150#issuecomment-2555548345), we should decide on which tool to use—Dependabot or Renovate—so that we don’t have to perform these version updates manually.

**Comment by wesleytodd** [comment]
Ah, just seeing this after checking the previous notification for updating. Sorry if that comment is not necessary now. Anyway, if this is a way to unblock those from failing I am good merging them, but we should work on a non-distributed way to manage these. Maybe have a shared workflow we update in one place?

**Comment by sheplu** [comment]
> Ah, just seeing this after checking the previous notification for updating. Sorry if that comment is not necessary now. Anyway, if this is a way to unblock those from failing I am good merging them, but we should work on a non-distributed way to manage these. Maybe have a shared workflow we update in one place?

one of the plan I have (and will be starting soon) is to centralize all workflows - allowing full reusability across all projects :D

**Comment by UlisesGascon** [comment]
### Bulk update

I started a bulk operation to update all the repos with the common OSSF Scorecard recommendations


#### Express Org
_Status: bulk completed_

- [ ] expressjs/expressjs.com#1905
- [ ] expressjs/cors#350
- [ ] expressjs/compression#235
- [ ] expressjs/response-time#37
- [ ] expressjs/basic-auth-connect#12
- [ ] expressjs/generator#336
- [ ] expressjs/multer#1311
- [ ] expressjs/serve-favicon#53
- [ ] expressjs/serve-index#119
- [ ] expressjs/cookie-parser#129
- [ ] expressjs/cookie-session#186
- [ ] expressjs/errorhandler#31
- [ ] expressjs/timeout#47
- [ ] expressjs/vhost#50
- [ ] expressjs/session#1047
- [ ] expressjs/method-override#19
- [ ] expressjs/morgan#300
- [ ] expressjs/codemod#55

#### Pillarjs Org
_Status: bulk in progress_

- [ ] pillarjs/parseurl#17

#### JsHttp Org
_Status: bulk not started_

**Comment by UlisesGascon** [comment]
All the PRs are merged, so technically this is completed! 🥳 

Thanks @inigomarquinez @carpasse @bjohansebas @Phillip9587 for the incredible support :heart:
